### ISSUE TITLE
Page number

### ISSUE THREAD

**Issue by chriscct7** [patrickhlauke/getting-touchy-presentation#11]
It'd be nice if the page number could be included on the pages.
Shower has this built in now as well as a progress bar, but I'm not sure if the version you're using is up to date yet (haven't checked).

**Comment by patrickhlauke** [comment]
Personally, I prefer just having the progress bar (mainly because it shocks attendees less when they're about to embark on a full-day workshop and they don't know that there are nearly 400 slides we'll be going through)
