### ISSUE TITLE
Slide switching on scroll(?)/tap(?) seems overly sensitive

### ISSUE THREAD

**Issue by cvrebert** [patrickhlauke/getting-touchy-presentation#2]
On my MacBook Pro, as soon as I put my 2nd finger down on the trackpad in preparation to initiate a right-click on a link in the presentation, the current slide immediately changes. One of the event listeners seems to be too sensitive.

**Comment by patrickhlauke** [comment]
Possibly an issue in https://github.com/shower ? Admittedly, I've not updated the Shower.js bits for absolute ages, so may already be resolved there and I just need to grab the latest version...

**Comment by cvrebert** [comment]
I don't experience the problem with the demo on http://shwr.me

**Comment by patrickhlauke** [comment]
Ok, I'll get onto updating the engine, hopefully that'll address this :+1:

**Comment by cvrebert** [comment]
Fix confirmed!

**Comment by cvrebert** [comment]
Also, did you happen to see my Slack message?

**Comment by patrickhlauke** [comment]
Incidentally, the source of the problem seemed to be Chrome's two-finger back/forward navigation http://apple.stackexchange.com/questions/21236/how-do-i-disable-chromes-two-finger-back-forward-navigation
