### ISSUE TITLE
Lazyload images to improve page performance

### ISSUE THREAD

**Issue by XhmikosR** [patrickhlauke/getting-touchy-presentation#5]
Currently there's 208 requests, 46.6MB!

http://tools.pingdom.com/fpt/#!/b9wwwD/https://patrickhlauke.github.io/getting-touchy-presentation/

Not sure what your internet connection is but here it takes a minute or more to load the page :/

I can put quickly a patch if needed.

**Comment by patrickhlauke** [comment]
heh, it's mainly because i use the presentation locally. would lazy loading also work with the index/slide overview page (when they're all shown small)?

but by all means, if you can give me a hint on how to easily lazy load, that'd be appreciated.

**Comment by XhmikosR** [comment]
I'll see what I can do in the next days. For starters, I'm optimizing the images; this should save a few megabytes.

Do you mind using jQuery?

**Comment by XhmikosR** [comment]
@patrickhlauke: do you mind using jQuery?

**Comment by patrickhlauke** [comment]
As long as I can still use the whole thing without needing to run grunt and stuff, I'm all for it ;)

**Comment by XhmikosR** [comment]
@patrickhlauke: I got it working successfully.

A couple of things:
1. Do you want a noscript fallback? My guess is no is shower won't work anyway
2. Should I add a fallback image? That's mostly so that the document is valid
3. You should update shower after my lazyload PR goes in
4. Maybe properly indent the markup
5. I refactored the assets in my PR

Only issue is the images don't show up if you visit a presentation without having scrolled to it first :/

You can see the changes:
https://github.com/patrickhlauke/getting-touchy-presentation/compare/gh-pages...XhmikosR:gh-pages
http://xhmikosr.io/getting-touchy-presentation/

**Comment by XhmikosR** [comment]
Only issue is the images don't show up if you visit a presentation without having scrolled to it first :/

**Comment by XhmikosR** [comment]
You can see the changes:
https://github.com/patrickhlauke/getting-touchy-presentation/compare/gh-pages...XhmikosR:gh-pages
http://xhmikosr.io/getting-touchy-presentation/

**Comment by XhmikosR** [comment]
Oh, and don't forget to resize background-cover.jpg and photos-ios-iphone-safari-history-swipe-gestures.jpg too.

**Comment by patrickhlauke** [comment]
Sadly going to close this for now, as the "having scrolled to it first" bit makes it a bit of a dealbreaker. Will see if I can somehow work out an alternative solution (possibly involving page visibility API)

**Comment by XhmikosR** [comment]
No worries, just have it in your low-priority todo list :)
